### ISSUE TITLE
Idea de pagina para cada miembro del grupo/comunidad

### ISSUE THREAD

**Issue by Edwing123** [yeho/webcomunidad#8]
Estaba pensando que seria cool crear una pagina de presentacion tipo perfil para cada miembro de la comunidad, bueno, realmente los miembros que esten interesados, los cuales creo son una gran mayoria.

Habria que ver que tipo de informacion habria que poner en tal pagina, yo podria pensar en ello, claro, si los admins/encargados me dan luz verde para proceder, sino, pues nomas no lo hago, y asi ver que otra cosas hacemos.

## Diseños que tengo en Figma

Hace un tiempo tuve la misma idea, y realice un diseño en Figma, hay cosas que ahora en dia puedo cambiar, pero ya seria un diseño inicial.

![Profile-profile](https://user-images.githubusercontent.com/40911825/185883798-e7c018b4-a55e-4b84-81d5-daf160afd275.png)

La informacion del perfil es estatica, y esta misma puede ser presentada con un objeto JSON, asi que cada miembro podria escribir un archivo JSON, el cual representara su informacion, un ejemplo seria:

```json
{
  "first_name": "Edwin",
  "last_name": "Garcia",
  "links": {
    "instagram": "https://instagram.com/foo",
    "github": "https://github.com/foo"
  },
  "role": "Frontend Developer",
  "description": "Hola! Mi nombre es Edwin Garica..."
}
```
Con este archivo, ya luego podemos construir la pagina para el miembro, ya sea de forma manual or usando algun motor de plantillas con Express.

Creo que para empezar, la estructura del JSON de arriba esta bien, ya el diseño se modificaria para adaptar esa informacion.

**Comment by yeho** [comment]
se cierra este issue para darle seguimiento al tema en el otro que se genero previamente 
**aqui el link** -->  https://github.com/yeho/webcomunidad/issues/7
